name: Android Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_RELEASE_KEYSTORE }}
        run: |
          echo "Decoding keystore"
          echo $ENCODED_KEYSTORE | base64 -d > android/app/release.keystore
          chmod 600 android/app/release.keystore

      - name: Create Keystore Properties
        env:
          KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: |
          cat <<EOF > android/keystore.properties
          MYAPP_RELEASE_STORE_FILE=release.keystore
          MYAPP_RELEASE_KEY_ALIAS=$KEY_ALIAS
          MYAPP_RELEASE_STORE_PASSWORD=$STORE_PASSWORD
          MYAPP_RELEASE_KEY_PASSWORD=$KEY_PASSWORD
          EOF

      - name: Create Environment File
        run: |
          echo "Creating .env file"
          cat <<EOF > .env
          APP_NAME=${{ secrets.APP_NAME }}
          GOOGLE_WEB_CLIENT_ID=${{ secrets.GOOGLE_WEB_CLIENT_ID }}
          EOF

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Set up JDK 17 (Required for Gradle 8.x)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: npm ci

      - name: Generate JS Bundle
        run: |
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res/

      - name: Fix Gradle permissions
        run: chmod +x android/gradlew

      - name: Clean Gradle
        run: cd android && ./gradlew clean

      - name: Build Android Release
        run: |
          cd android
          ./gradlew assembleRelease \
            --warning-mode all \
            -Dorg.gradle.java.home=$JAVA_HOME_17_X64

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: |
            android/app/build/outputs/apk/release/*.apk
            android/app/build/outputs/bundle/release/*.aab

      - name: Upload Build Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: android/build/reports/
